### PR TITLE
Defensive programming

### PR DESCRIPTION
**Pull request by bell87**
Added an if statement to return early when "_assessmentId" isn't set. This will prevent a JS error which stops the course page from loading.

### CODE REVIEW

**Comment by ryangadams** [comment]
+1

**Comment by tomgreenfield** [comment]
Hi @bell87, what are the steps to replicate this please? This existing logic on [line 40](https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/master/js/adapt-contrib-assessmentResults.js#L40) seems to stop anything untoward for me:
```js
if (!assessmentModel || assessmentModel.length === 0) return;
```

**Comment by bell87** [comment]
Hi @tomgreenfield - If I add an assessment results component to a course, save and preview then when the course component loads it hangs on a JS error because `this.model.get("_assessmentId")` is `undefined` or `""`

**Comment by tomgreenfield** [comment]
It actually looks to be erroring when it can't find the `Adapt.assessment` object. Have you got the Assessment extension enabled? It may be worthwhile to put in a check for this in the code instead.

**Comment by brian-learningpool** [comment]
+1

**Comment by tomgreenfield** [comment]
+1

**Pull request merged**
