### PR TITLE
Removed redundant condition

### PR DESCRIPTION
**Pull request by chris-steele**

### CODE REVIEW

**Comment by moloko** [comment]
+1

**Comment by tomgreenfield** [comment]
Any chance https://github.com/adaptlearning/adapt_framework/issues/943 could be fixed while we're here?

**Comment by oliverfoster** [comment]
It'd be better to remove the containing if statement to make that expression valid. Then we can do 943 by restoring the title, body + instruction on reset.

**Comment by moloko** [comment]
presumably #20 has removed the need for this now?

**Pull request closed without merging**
