### PR TITLE
issue fixes

### PR DESCRIPTION
**Pull request by sarveshwar-gavhane**
ensure that assessment results will be reset if following settings are enabled.

1. Reset on Revisit
2. Allow retry once passed

### CODE REVIEW

**Comment by moloko** [comment]
need to do a bit more testing but I think this causes problems when you revisit an assessment page from an LMS when `_shouldStoreResponses` is enabled

**Comment by moloko** [comment]
So, if I have:
* `_spoor._tracking._shouldSubmitScore: true`
* `_assessment._allowResetIfPassed: true`
* `_assessment._isResetOnRevisit: false`

i.e. I want the user's question responses to be remembered between sessions and I want them to be able to reset if they pass - but only via the 'Retry' button in the assessment results.

Then, if I pass the assessment, quit and relaunch the bookmarking extension takes me back to the assessment, all the responses are restored but the assessment results component looks like this:
image

**Comment by sarveshwar-gavhane** [comment]
well caught @moloko, in that we have to consider `_assessment._isResetOnRevisit: false` attribute.

**Comment by moloko** [comment]
@sarveshwar-gavhane my current thinking is the fix might need to be in the assessment extension rather than this component. The reason this component isn't doing what it should is because when a previously-passed assessment does a 'reset on revisit' the assessment extension is triggering an `assessments:complete` event just after the `assessments:reset` event.

**Comment by sarveshwar-gavhane** [comment]
i checked quickly,  i think when we revisit the course assessment extension doesn't trigger for `assessment: complete`, this line https://github.com/adaptlearning/adapt-contrib-assessmentResults/blob/master/js/assessmentResultsView.js#L24 of statement is reponsible for triggering/checking completion.

if we have,

scenario 1: in this case assessment as well as assessment Result will reset, as expected

1. `_spoor._shouldStoreResponses : true`
2. `_spoor._tracking._shouldSubmitScore: true`
3.  `_assessment._allowResetIfPassed: true`
4.  `_assessment._isResetOnRevisit: true`

scenario 2:

1. `_spoor._shouldStoreResponses : true`
2. `_spoor._tracking._shouldSubmitScore: true`
3.  `_assessment._allowResetIfPassed: true`
4.  `_assessment._isResetOnRevisit: false`

in this case user's question responses would be remembered between sessions and user can be able to reset if they pass - but only via the 'Retry' button in the assessment results, even if he pass the assessment, quit and relaunch again.

i think this fix needs to be in assessment Result with below line of code:

`var isResetOnRevisit = assessmentModel.get('_assessment')._isResetOnRevisit;
if (state.isComplete && (!state.allowResetIfPassed || !isResetOnRevisit)) {
     this.onAssessmentComplete(state);
     return;
}`

**Pull request merged**
